const goodMap=
    { 
     id: "101",
     index:{ "name": "阿炳牛杂", 
     "address": "广东省广州市越秀区中山五路219号华联购物中心F1",
     "id": "101", 
     "phone": "13437850035", 
     "category": [{"text":"快餐便当"},{"text":"简餐"},{"text":"套餐"},{"text":"炖品"},{"text":"其他"}], 
     "good": {
     "A":[
          {"name": "南瓜粥",
          "gid":"a311",
          "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
          "price": 19,
          "description": "甜粥",
          "sellCount": 91,
          "rating": 100,
         },
       { "name": "南瓜饭",
       "gid":"a312",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
         "price": 9,
         "description": "甜粥",
         "sellCount": 91,
         "rating": 100,
        },
       { "name": "苦瓜粥",
       "gid":"a315",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 11,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },
        { "name": "西瓜粥",
        "gid":"a313",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 3,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },
        { "name": "特热粥",
        "gid":"a213",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 4,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },],
        "B":[
          {"name": "南瓜粥",
          "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
          "price": 9,
          "description": "甜粥",
          "sellCount": 91,
          "rating": 100,
         },
       { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
         "price": 9,
         "description": "甜粥",
         "sellCount": 91,
         "rating": 100,
        },
       { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },
        { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },
        { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },],
        "C":[
          {"name": "南瓜粥",
          "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
          "price": 9,
          "description": "甜粥",
          "sellCount": 91,
          "rating": 100,
         },
       { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
         "price": 9,
         "description": "甜粥",
         "sellCount": 91,
         "rating": 100,
        },
       { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },
        { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },
        { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },],
        "D":[
          {"name": "南瓜粥",
          "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
          "price": 9,
          "description": "甜粥",
          "sellCount": 91,
          "rating": 100,
         },
       { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
         "price": 9,
         "description": "甜粥",
         "sellCount": 91,
         "rating": 100,
        },
       { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },
        { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },
        { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },],
        "E":[
          {"name": "南瓜粥",
          "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
          "price": 9,
          "description": "甜粥",
          "sellCount": 91,
          "rating": 100,
         },
       { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
         "price": 9,
         "description": "甜粥",
         "sellCount": 91,
         "rating": 100,
        },
       { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },
        { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },
        { "name": "南瓜粥",
        "picture": "http://static.galileo.xiaojukeji.com/static/tms/default_header.png",
        "price": 9,
        "description": "甜粥",
        "sellCount": 91,
        "rating": 100,
        },],
        }, 
"supports": [{ "description": "已加入“外卖保”计划，食品安全有保障", "icon_color": "999999", "icon_name": "保", "id": 7, "name": "外卖保", "_id": "5a5859a19c2bc57d52df30b3" }, { "description": "准时必达，超时秒赔", "icon_color": "57A9FF", "icon_name": "准", "id": 9, "name": "准时达", "_id": "5a5859a19c2bc57d52df30b2" }, { "description": "该商家支持开发票，请在下单时填写好发票抬头", "icon_color": "999999", "icon_name": "票", "id": 4, "name": "开发票", "_id": "5a5859a19c2bc57d52df30b1" }], 
"status": 1, 
"promotion_info": "欢迎光临，用餐高峰请提前下单，谢谢",
 "piecewise_agent_fee": { "tips": "配送费约¥5" }, 
 "opening_hours": ["8:30/20:30"], 
 "license": { "catering_service_license_image": "160e91e17fa2164.png", "business_license_image": "160e91e0a9f2163.png" },
  "is_new": true, 
  "is_premium": true,
   "image_path": "https://dss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=1305353222,2352820043&fm=26&gp=0.jpg",
   "identification": { 
       "registered_number": "", 
       "registered_address": "", 
       "operation_period": "", 
       "licenses_scope": "", 
       "licenses_number": "", 
       "licenses_date": "", 
       "legal_person": "", 
       "identificate_date": null, 
       "identificate_agency": "", 
       "company_name": "" 
    }, 
    "float_minimum_order_amount": 20, 
    "float_delivery_fee": 5, 
    "distance": "9.1公里", 
    "order_lead_time": "26分钟", 
    "description": "sad", 
}}


export default {
     showgoodlists(res){
          console.log(goodMap)
        if(goodMap.body===res.id)
          {
               
               return goodMap.index
     }
}
}